In [14]:
import pandas as pd
import numpy as np
import re

In [28]:
# Load the content from your file
def time_to_first_token_seconds(file_path):
    with open(file_path, 'r') as f:
        lines = f.readlines()
    
    timestamp = []
    log = []
    
    for line in lines:
        line = line.strip()
        if "Dec 17" in line:
            timestamp.append(line)
        else:
            log.append(line)
    
    df = pd.DataFrame({"timestamp": timestamp, "log": log})

    keywords = "Received request|Generated response"
    df = df[df['log'].str.contains(keywords, na=False)].reset_index(drop=True)
    conditions = [
        df['log'].str.contains("Received request", na=False),
        df['log'].str.contains("Generated response", na=False)
    ]
    choices = ['received', 'generated']
    df['type'] = np.select(conditions, choices, default="others")
    df = df[df.type.isin(choices)]

    df['dt'] = pd.to_datetime(df['timestamp'], format='%b %d %H:%M:%S.%f')
    df['time_to_first_token_seconds'] = (df['dt'].shift(-1) - df['dt']).dt.total_seconds()
    df = df[df['type'] == 'received'][['timestamp', 'type', 'time_to_first_token_seconds', 'log']]

    return df

In [29]:
time_to_first_token_seconds('what_is_sunflower.txt')

,timestamp,type,time_to_first_token_seconds,log
0,Dec 17 16:46:47.223,received,8.470,(APIServer pid=5) INFO 12-17 13:46:47 [logger....
7,Dec 17 16:46:58.867,received,0.055,(APIServer pid=5) INFO 12-17 13:46:58 [logger....
14,Dec 17 16:47:03.881,received,0.054,(APIServer pid=5) INFO 12-17 13:47:03 [logger....
21,Dec 17 16:47:06.461,received,0.054,(APIServer pid=5) INFO 12-17 13:47:06 [logger....
28,Dec 17 16:47:09.050,received,0.053,(APIServer pid=5) INFO 12-17 13:47:09 [logger....
35,Dec 17 16:47:11.549,received,0.059,(APIServer pid=5) INFO 12-17 13:47:11 [logger....
42,Dec 17 16:47:14.352,received,0.054,(APIServer pid=5) INFO 12-17 13:47:14 [logger....
49,Dec 17 16:47:17.346,received,0.056,(APIServer pid=5) INFO 12-17 13:47:17 [logger....
56,Dec 17 16:47:19.883,received,0.055,(APIServer pid=5) INFO 12-17 13:47:19 [logger....
63,Dec 17 16:47:22.583,received,0.055,(APIServer pid=5) INFO 12-17 13:47:22 [logger....
70,Dec 17 16:47:25.127,received,0.061,(APIServer pid=5) INFO 12-17 13:47:25 [logger....
77,Dec 17 16:47:27.579,received,0.057,(APIServer pid=5) INFO 12-17 13:47:27 [logger....
84,Dec 17 16:47:32.780,received,0.055,(APIServer pid=5) INFO 12-17 13:47:32 [logger....
91,Dec 17 16:47:35.350,received,0.054,(APIServer pid=5) INFO 12-17 13:47:35 [logger....
98,Dec 17 16:47:37.760,received,0.053,(APIServer pid=5) INFO 12-17 13:47:37 [logger....
105,Dec 17 16:47:40.360,received,0.055,(APIServer pid=5) INFO 12-17 13:47:40 [logger....
112,Dec 17 16:47:43.441,received,0.059,(APIServer pid=5) INFO 12-17 13:47:43 [logger....
119,Dec 17 16:47:47.344,received,0.054,(APIServer pid=5) INFO 12-17 13:47:47 [logger....
126,Dec 17 16:47:51.776,received,0.056,(APIServer pid=5) INFO 12-17 13:47:51 [logger....
133,Dec 17 16:47:54.418,received,0.055,(APIServer pid=5) INFO 12-17 13:47:54 [logger....

In [30]:
time_to_first_token_seconds('context_eng_1.txt')

,timestamp,type,time_to_first_token_seconds,log
0,Dec 17 16:54:26.871,received,8.205,(APIServer pid=5) INFO 12-17 13:54:26 [logger....
77,Dec 17 16:55:31.381,received,0.053,(APIServer pid=5) INFO 12-17 13:55:31 [logger....
153,Dec 17 16:55:39.345,received,0.054,(APIServer pid=5) INFO 12-17 13:55:39 [logger....
230,Dec 17 16:56:13.369,received,0.054,(APIServer pid=5) INFO 12-17 13:56:13 [logger....
307,Dec 17 16:56:20.816,received,0.054,(APIServer pid=5) INFO 12-17 13:56:20 [logger....
384,Dec 17 16:56:28.076,received,0.054,(APIServer pid=5) INFO 12-17 13:56:28 [logger....
460,Dec 17 16:57:06.922,received,0.054,(APIServer pid=5) INFO 12-17 13:57:06 [logger....
538,Dec 17 16:57:14.621,received,0.054,(APIServer pid=5) INFO 12-17 13:57:14 [logger....
615,Dec 17 16:57:21.380,received,0.053,(APIServer pid=5) INFO 12-17 13:57:21 [logger....
692,Dec 17 16:57:28.986,received,0.053,(APIServer pid=5) INFO 12-17 13:57:28 [logger....
769,Dec 17 16:57:36.108,received,0.054,(APIServer pid=5) INFO 12-17 13:57:36 [logger....
845,Dec 17 16:57:43.565,received,0.053,(APIServer pid=5) INFO 12-17 13:57:43 [logger....
921,Dec 17 16:58:24.471,received,0.054,(APIServer pid=5) INFO 12-17 13:58:24 [logger....
998,Dec 17 16:58:34.169,received,0.054,(APIServer pid=5) INFO 12-17 13:58:34 [logger....
1073,Dec 17 16:58:41.496,received,0.052,(APIServer pid=5) INFO 12-17 13:58:41 [logger....
1150,Dec 17 16:58:49.033,received,0.053,(APIServer pid=5) INFO 12-17 13:58:49 [logger....
1226,Dec 17 16:58:56.196,received,0.054,(APIServer pid=5) INFO 12-17 13:58:56 [logger....
1303,Dec 17 16:59:03.363,received,0.054,(APIServer pid=5) INFO 12-17 13:59:03 [logger....
1379,Dec 17 16:59:10.335,received,0.052,(APIServer pid=5) INFO 12-17 13:59:10 [logger....
1456,Dec 17 16:59:17.664,received,0.054,(APIServer pid=5) INFO 12-17 13:59:17 [logger....

In [ ]:
df.